/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemadminworkarea;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.geography.Country;
import business.organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import userinterface.personrole.PersonWorkAreaJPanel;
import userinterface.reportresult.HealthInsuranceReport;

/**
 *
 * @author Parth, Nikhil, Praneeth
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        populateJTree();
    }

    public void populateJTree() {
        DefaultTreeModel model = (DefaultTreeModel) ecosystemJTree.getModel();

        ArrayList<Country> countryList = ecoSystem.getCountryList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList organizationList;

        Country country;
        Enterprise enterprise;
        Organization organization;
 
        DefaultMutableTreeNode countrys = new DefaultMutableTreeNode("COUNTIRES");
        //DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        DefaultMutableTreeNode rootnode = new DefaultMutableTreeNode("ECOSYSTEM"); 
        DefaultTreeModel treeModel = new DefaultTreeModel(rootnode); 
        ecosystemJTree.setModel(treeModel); 
        rootnode.removeAllChildren();
        rootnode.insert(countrys, 0);

        DefaultMutableTreeNode countryNode, enterpriseNode, organizationNode;

        for (int i = 0; i < countryList.size(); i++) {
            country = countryList.get(i);
            countryNode = new DefaultMutableTreeNode(country.getName());
            countrys.insert(countryNode, i);

            enterpriseList = country.getEnterpriseDirectory().getEnterpriseDirectory();

            for (int j = 0; j < enterpriseList.size(); j++) {
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                countryNode.insert(enterpriseNode, j);
                
                if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Government)) {
                    organizationList = enterprise.getOrganizationDirectory().getGovernmentOrganizationDirectory();
                } else {
                    organizationList = enterprise.getOrganizationDirectory().getHospitalOrganizationDirectory();
                }                

                for (int k = 0; k < organizationList.size(); k++) {
                    organization = (Organization) organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }
        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ecosystemJTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        manageCountryJButton = new javax.swing.JButton();
        manageEnterpriseAdminJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        selectedNodeJLabel = new javax.swing.JLabel();
        viewSelectedNodeJLabel = new javax.swing.JLabel();
        outputButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        ecosystemJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                ecosystemJTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ecosystemJTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        manageCountryJButton.setBackground(new java.awt.Color(0, 0, 0));
        manageCountryJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageCountryJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageCountryJButton.setText("Manage Country");
        manageCountryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCountryJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseAdminJButton.setBackground(new java.awt.Color(0, 0, 0));
        manageEnterpriseAdminJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageEnterpriseAdminJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseAdminJButton.setText("Manage Enterprise Admin");
        manageEnterpriseAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseJButton.setBackground(new java.awt.Color(0, 0, 0));
        manageEnterpriseJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageEnterpriseJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });

        selectedNodeJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        selectedNodeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectedNodeJLabel.setText("Selected :");

        viewSelectedNodeJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewSelectedNodeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewSelectedNodeJLabel.setText("<view_selected_node>");

        outputButton.setBackground(new java.awt.Color(0, 0, 0));
        outputButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        outputButton.setForeground(new java.awt.Color(255, 255, 255));
        outputButton.setText("OUTPUT REPORTS SCREEN");
        outputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(selectedNodeJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(viewSelectedNodeJLabel)
                        .addContainerGap(558, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageEnterpriseAdminJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageCountryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedNodeJLabel)
                    .addComponent(viewSelectedNodeJLabel))
                .addGap(50, 50, 50)
                .addComponent(manageCountryJButton)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(manageEnterpriseJButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(outputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(manageEnterpriseAdminJButton)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageCountryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCountryJButtonActionPerformed
        // TODO add your handling code here:
        ManageCountryJPanel panel = new ManageCountryJPanel(userProcessContainer, ecoSystem, this);
        userProcessContainer.add("ManageCountryJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCountryJButtonActionPerformed

    private void manageEnterpriseAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel panel = new ManageEnterpriseAdminJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add("ManageEnterpriseAdminJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed
        ManageEnterpriseJPanel panel = new ManageEnterpriseJPanel(userProcessContainer, ecoSystem, this);
        userProcessContainer.add("ManageEnterpriseJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void ecosystemJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_ecosystemJTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) ecosystemJTree.getLastSelectedPathComponent();
        if (selectedNode != null) {
            viewSelectedNodeJLabel.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_ecosystemJTreeValueChanged

    private void outputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputButtonActionPerformed
        // TODO add your handling code here:
        
        
          HealthInsuranceReport panel = new HealthInsuranceReport(userProcessContainer);
        userProcessContainer.add("healthInsuranceReport", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_outputButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree ecosystemJTree;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageCountryJButton;
    private javax.swing.JButton manageEnterpriseAdminJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton outputButton;
    private javax.swing.JLabel selectedNodeJLabel;
    private javax.swing.JLabel viewSelectedNodeJLabel;
    // End of variables declaration//GEN-END:variables
}
