/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.labRole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.geography.City;
import business.geography.State;
import business.geography.Country;
import business.organization.Organization;

import business.useraccount.UserAccount;
import business.workqueue.LabOrderWorkList;
import business.workqueue.LabOrderWorkRequest;
//import com.sun.xml.internal.org.jvnet.fastinfoset.stax.LowLevelFastInfosetStreamWriter;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prane
 */
public class LabpersonWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    


    /**
     * Creates new form LabpersonWorkAreaJPanel
     */
    public LabpersonWorkAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = useraccount;
      
        populateTable(enterprise.laborderWorkList);
    }
    
    private void populateTable(LabOrderWorkList lowl)
    {
        DefaultTableModel dtm = (DefaultTableModel) TasksJTable.getModel();
        dtm.setRowCount(0);

        for (LabOrderWorkRequest req : lowl.getLabworklist())
        {
            Object row[] = new Object[4];
            row[0] = req;
            row[1] = req.getRequestID();
            row[2] = req.getOrdername();
            row[3] = req.getPrioritylevel();
            dtm.addRow(row);           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TasksJTable = new javax.swing.JTable();
        SubmitResultButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        LabNotesTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));

        TasksJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Test Detail", "ID", "Order Name", "Priority"
            }
        ));
        jScrollPane1.setViewportView(TasksJTable);

        SubmitResultButton.setBackground(new java.awt.Color(0, 0, 0));
        SubmitResultButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitResultButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitResultButton.setText("Submit Results");
        SubmitResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitResultButtonActionPerformed(evt);
            }
        });

        LabNotesTextArea.setColumns(20);
        LabNotesTextArea.setRows(5);
        jScrollPane2.setViewportView(LabNotesTextArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Notes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pending Orders to be Resulted");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(SubmitResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(SubmitResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitResultButtonActionPerformed
        // TODO add your handling code here:
int selectedRow = TasksJTable.getSelectedRow();
        if (selectedRow < 0) 
        {
            JOptionPane.showMessageDialog(null, "Please select a row first", null, 0);
        } 
        else 
        {
            LabOrderWorkRequest lowr = (LabOrderWorkRequest) TasksJTable.getValueAt(selectedRow, 0);
            lowr.setResults(LabNotesTextArea.getText());
            
            JOptionPane.showMessageDialog(null, "Results processed for this Order", null, 1);
        }
        
    }//GEN-LAST:event_SubmitResultButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea LabNotesTextArea;
    private javax.swing.JButton SubmitResultButton;
    private javax.swing.JTable TasksJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
