/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.administrativeRole;

import business.enterprise.Enterprise;
import business.organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Parth, Nikhil, Praneeth
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
        populateOrganizationTypeComboBox();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) organizationJTable.getModel();
        dtm.setRowCount(0);

        Object[] row = new Object[2];

        if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Government)) {
            for (Organization organization : enterprise.getOrganizationDirectory().getGovernmentOrganizationDirectory()) {
                row[0] = organization.getOrganizationID();
                row[1] = organization;
                dtm.addRow(row);
                
            }}
         if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Medical)) {
            for (Organization organization : enterprise.getOrganizationDirectory().getHospitalOrganizationDirectory()) {
                row[0] = organization.getOrganizationID();
                row[1] = organization;
                dtm.addRow(row);
            }
              for (Organization organization : enterprise.getOrganizationDirectory().getLabOrganizationDirectory()) {
                row[0] = organization.getOrganizationID();
                row[1] = organization;
                dtm.addRow(row);
            }}
         

        }
    
    public void populateOrganizationTypeComboBox() {

        if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Government)) {
            for (Organization.GovernmentOrganizationType type : Organization.GovernmentOrganizationType.values()) {
                organizationJComboBox.addItem(type);
            }}
             if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Medical)) {
            for (Organization.MedicalInstituteOrganizationType type : Organization.MedicalInstituteOrganizationType.values()) {
                organizationJComboBox.addItem(type);
            } 
            
        } 
        

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        addNewOrganizationJLabel = new javax.swing.JLabel();
        organizationTypeJLabel = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        addOrganizationJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORGANIZATION ID", "ORGANIZATION NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        addNewOrganizationJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addNewOrganizationJLabel.setForeground(new java.awt.Color(255, 255, 255));
        addNewOrganizationJLabel.setText("ADD NEW ORGANIZATION:");

        organizationTypeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        organizationTypeJLabel.setText("ORGANIZATION TYPE:");

        addOrganizationJButton.setBackground(new java.awt.Color(0, 0, 0));
        addOrganizationJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addOrganizationJButton.setForeground(new java.awt.Color(255, 255, 255));
        addOrganizationJButton.setText("ADD ORGANIZATION");
        addOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizationJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewOrganizationJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(organizationTypeJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(addNewOrganizationJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationTypeJLabel))
                .addGap(18, 18, 18)
                .addComponent(addOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizationJButtonActionPerformed
        if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Medical)) {
            Organization.MedicalInstituteOrganizationType type = (Organization.MedicalInstituteOrganizationType) organizationJComboBox.getSelectedItem();
            enterprise.getOrganizationDirectory().createAnHospitalOrganization(type);
            populateTable();
        }
        if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Medical)) {
            Organization.MedicalInstituteOrganizationType type = (Organization.MedicalInstituteOrganizationType) organizationJComboBox.getSelectedItem();
            enterprise.getOrganizationDirectory().createAnLabOrganization(type);
            populateTable();
        }
        else {
            Organization.GovernmentOrganizationType type = (Organization.GovernmentOrganizationType) organizationJComboBox.getSelectedItem();
            enterprise.getOrganizationDirectory().createAGovernmentOrganization(type);
            populateTable();
        }
    }//GEN-LAST:event_addOrganizationJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNewOrganizationJLabel;
    private javax.swing.JButton addOrganizationJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JLabel organizationTypeJLabel;
    // End of variables declaration//GEN-END:variables
}
