/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import business.EcoSystem;
import userinterface.DoctorRole.ExaminePatientJPanel;
import userinterface.DoctorRole.TreatPatientJPanel;
import business.enterprise.Enterprise;
import business.geography.City;
import business.geography.State;
import business.geography.Country;
import business.neuralnetworks.lungCancer;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import weka.classifiers.Classifier;
import weka.classifiers.lazy.IBk;
import weka.core.Instance;
import weka.core.Instances;

/**
 *
 * @author prane
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount useraccount;
    private Organization organization;
    private Country country;
    private State state;
    private City city;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, Organization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
        this.country = country;
        this.state = state;
        this.city = city;
        this.organization = organization;
        enterpriseValueJLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeAsAnAdminJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        enterpriseValueJLabel = new javax.swing.JLabel();
        diagnosePatientJButton = new javax.swing.JButton();
        predictjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        predictjTextArea = new javax.swing.JTextArea();
        placeLabRequestButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        welcomeAsAnAdminJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcomeAsAnAdminJLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeAsAnAdminJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeAsAnAdminJLabel.setText("WELCOME DOCTOR");

        enterpriseNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseNameJLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseNameJLabel.setText("ENTERPRISE NAME:");

        enterpriseValueJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseValueJLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseValueJLabel.setText("<value>");

        diagnosePatientJButton.setBackground(new java.awt.Color(0, 0, 0));
        diagnosePatientJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diagnosePatientJButton.setForeground(new java.awt.Color(255, 255, 255));
        diagnosePatientJButton.setText("Reasearch");
        diagnosePatientJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        diagnosePatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosePatientJButtonActionPerformed(evt);
            }
        });

        predictjButton.setBackground(new java.awt.Color(0, 0, 0));
        predictjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        predictjButton.setForeground(new java.awt.Color(255, 255, 255));
        predictjButton.setText("Predict for lung cancer patients");
        predictjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        predictjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictjButtonActionPerformed(evt);
            }
        });

        predictjTextArea.setColumns(20);
        predictjTextArea.setLineWrap(true);
        predictjTextArea.setRows(5);
        predictjTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(predictjTextArea);

        placeLabRequestButton.setBackground(new java.awt.Color(0, 0, 0));
        placeLabRequestButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeLabRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        placeLabRequestButton.setText("Lab Order Request");
        placeLabRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeLabRequestButtonActionPerformed(evt);
            }
        });

        reportsButton.setBackground(new java.awt.Color(0, 0, 0));
        reportsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportsButton.setForeground(new java.awt.Color(255, 255, 255));
        reportsButton.setText("Check Reports");
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeAsAnAdminJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(reportsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(predictjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diagnosePatientJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(placeLabRequestButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(enterpriseValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeAsAnAdminJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseValueJLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(placeLabRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diagnosePatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(predictjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void diagnosePatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosePatientJButtonActionPerformed

        JOptionPane.showMessageDialog(null, "Research on different forms of cancer is in process!");
//        // TODO add your handling code here:
//        userProcessContainer.add("ManageEmployeeJPanel", panel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_diagnosePatientJButtonActionPerformed

    private void predictjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictjButtonActionPerformed

        String outputBuffer = (new lungCancer()).run();
        predictjTextArea.setText(outputBuffer);

        // TODO add your handling code here:
    }//GEN-LAST:event_predictjButtonActionPerformed

    private void placeLabRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeLabRequestButtonActionPerformed
        // TODO add your handling code here:

        ExaminePatientJPanel panel = new ExaminePatientJPanel(userProcessContainer, useraccount, organization, enterprise);
//PlaceOrderJPanel panel = new PlaceOrderJPanel(userProcessContainer, useraccount,organization, enterprise );
        userProcessContainer.add("ExaminePatientJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_placeLabRequestButtonActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        // TODO add your handling code here:
        
        TreatPatientJPanel panel = new TreatPatientJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("TreatPatientJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diagnosePatientJButton;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JLabel enterpriseValueJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeLabRequestButton;
    private javax.swing.JButton predictjButton;
    private javax.swing.JTextArea predictjTextArea;
    private javax.swing.JButton reportsButton;
    private javax.swing.JLabel welcomeAsAnAdminJLabel;
    // End of variables declaration//GEN-END:variables
}
